# Generated by Django 2.0.3 on 2019-10-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpizza',
            old_name='name',
            new_name='type',
        ),
    ]
