# Generated by Django 2.2.6 on 2019-10-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191030_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='pizzatype',
            old_name='types',
            new_name='name',
        ),
        migrations.AddField(
            model_name='toppings',
            name='steak_subs_extra',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppings',
            name='subs_extra',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdinnerplatters',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='orderpasta',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ordersalads',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.RenameModel(
            old_name='SubType',
            new_name='SubsType',
        ),
        migrations.DeleteModel(
            name='OrderSub',
        ),
        migrations.DeleteModel(
            name='SubExtra',
        ),
        migrations.AddField(
            model_name='ordersubs',
            name='extra',
            field=models.ForeignKey(limit_choices_to={'subs_extra': True}, on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='ordersubs',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SubsType'),
        ),
        migrations.AddField(
            model_name='ordersubs',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AddField(
            model_name='ordersubs',
            name='steak_extra',
            field=models.ForeignKey(limit_choices_to={'steak_subs_extra': True}, on_delete=django.db.models.deletion.CASCADE, related_name='steak_extras', to='orders.Toppings'),
        ),
    ]
