# Generated by Django 2.2.6 on 2019-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191030_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='steak_subs_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='subs_extra',
            field=models.BooleanField(default=True),
        ),
    ]
