# Generated by Django 2.1.5 on 2019-11-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191030_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlattersType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='orderdinnerplatters',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DinnerPlattersType'),
        ),
    ]
