# Generated by Django 2.1.5 on 2019-11-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20191104_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item',
        ),
    ]
