# Generated by Django 2.0.3 on 2019-10-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191030_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpizza',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizzatype',
            old_name='name',
            new_name='types',
        ),
    ]
