# Generated by Django 2.2.6 on 2019-10-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191030_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='steak_subs_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='subs_extra',
            field=models.BooleanField(default=False),
        ),
    ]
