# Generated by Django 2.2.6 on 2019-10-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191030_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdinnerplatters',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderpasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordersalads',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordersubs',
            name='price',
            field=models.FloatField(),
        ),
    ]
