# Generated by Django 2.2.6 on 2019-10-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191030_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersubs',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='ordersubs',
            name='steak_extra',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='steak_subs_extra',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='subs_extra',
        ),
    ]
