# Generated by Django 2.2.6 on 2019-10-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191030_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='substype',
            name='steak_subs_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='substype',
            name='subs_extra',
            field=models.BooleanField(default=False),
        ),
    ]
