# Generated by Django 2.2.6 on 2019-11-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dish',
            field=models.CharField(choices=[('s', 'sub'), ('p', 'pizza')], default='s', max_length=1),
        ),
    ]
