# Generated by Django 2.1.5 on 2019-11-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_ordersubsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersubsx',
            name='ref',
            field=models.CharField(default='na', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordersubsx',
            name='name',
            field=models.ForeignKey(limit_choices_to=models.Q(('subs_extra', True), ('steak_subs_extra', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='orders.SubsType'),
        ),
    ]
