# Generated by Django 2.2.6 on 2019-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191104_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subx',
            field=models.ManyToManyField(blank=True, to='orders.OrderSubsX'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'small'), ('l', 'large')], default='', max_length=1),
        ),
    ]
