# Generated by Django 2.2.6 on 2019-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20191106_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='subx',
            field=models.ManyToManyField(blank=True, to='orders.SubsType'),
        ),
    ]
