# Generated by Django 2.2.6 on 2019-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20191106_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subx',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('subs_extra', True), ('steak_subs_extra', True), _connector='OR'), to='orders.SubsType'),
        ),
    ]
