# Generated by Django 2.1.5 on 2019-11-07 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0032_auto_20191106_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'pending'), ('s', 'submitted'), ('pr', 'processing'), ('c', 'completed')], default='p', max_length=2),
        ),
    ]
