# Generated by Django 2.1.5 on 2019-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20191107_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'small'), ('L', 'large')], default='s', max_length=1),
        ),
    ]
