# Generated by Django 2.1.5 on 2019-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20191107_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'small'), ('L', 'large')], default='S', max_length=1),
        ),
    ]
