# Generated by Django 2.1.5 on 2019-11-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20191108_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedToOrder', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('s', 'submitted'), ('p', 'processing'), ('c', 'completed')], default='p', max_length=1),
        ),
    ]
