# Generated by Django 2.1.5 on 2019-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20191108_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('s', 'submitted'), ('pr', 'processing'), ('c', 'completed')], default='p', max_length=2),
        ),
    ]
