# Generated by Django 2.2.6 on 2019-11-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20191108_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('s', 'Submitted'), ('pr', 'Processing'), ('c', 'Completed')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('s', 'Submitted'), ('pr', 'Processing'), ('c', 'Completed')], default='p', max_length=2),
        ),
    ]
