# Generated by Django 2.1.5 on 2019-11-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20191109_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_change_status', 'Change order status'),)},
        ),
    ]
