# Generated by Django 2.2.6 on 2020-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20191112_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'Please choose size'), ('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
